/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    views: [
        'LoadingPanel'
    ],
    icon: 'resources/themes/images/default/loading/loading_logo.png',
    name: 'Betit',

    launch: function() {
        // probably desktop browser, so simulate iPhone layout


        Ext.Viewport.on({
            'resize': function(c, o){
                Ext.Viewport.getActiveItem().fireEvent("painted", Ext.Viewport.getActiveItem());

            }
        });


        if (Ext.feature.has.Orientation){

        }

        Ext.Viewport.on({
            'orientationchange': function(c, o, w, h, e){


                if(o == 'portrait'){
                    Ext.getCmp("loading-panel").setIsfirsttime(true);
                }
                else
                Ext.getCmp("loading-panel").setIsfirsttime(false);
            }
        });
        Ext.create('Betit.view.LoadingPanel', {fullscreen: true});
    }

});
